### ISSUE TITLE
examples/launch_counters.py throw an exception

### ISSUE THREAD

**Issue by left4taco** [ros2/launch#149]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - From source
- Version or commit hash:
  - a46aabdde1f58c7e2e5c056c0c4a1ea830faac5c
- DDS implementation:
  - Fast-RTPS, but shouldn't matter here
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
```
$ cd <path-to-launch>/launch/examples
$  python3 ./launch_counters.py 
```

#### Expected behavior
Script runs successfully
#### Actual behavior
```sh
[ERROR] [launch]: exception occurred while executing process[whoami-1]:
Traceback (most recent call last):
  File "./../launch/actions/execute_process.py", line 423, in __execute_process
    stderr_to_stdout=(self.__output == 'screen'),
  File "<path-to-workspace>/install/lib/python3.5/site-packages/osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py", line 140, in async_execute_process
    stderr_to_stdout)
  File "<path-to-workspace>/install/lib/python3.5/site-packages/osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py", line 48, in _async_execute_process_nopty
    stderr=stderr, close_fds=False)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1079, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 184, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.5/asyncio/base_subprocess.py", line 40, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 649, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'time'
```

**Comment by wjwwood** [comment]
What shell are you using? The issue is that it is not finding `time` which is pretty standard on Linux. See:

https://github.com/ros2/launch/blob/a46aabdde1f58c7e2e5c056c0c4a1ea830faac5c/launch/examples/launch_counters.py#L66

**Comment by left4taco** [comment]
@wjwwood Thanks. I'm using bash and `time` is a shell reserved word, not an executable. That's probably the reason.

**Comment by wjwwood** [comment]
It might need `shell=True`, I can check later. I believe it's an executable `time` for `zsh`.

**Comment by wjwwood** [comment]
@left4taco can you try this diff?

```diff
diff --git a/launch/examples/launch_counters.py b/launch/examples/launch_counters.py
index fbbcdaa..bad0f3d 100755
--- a/launch/examples/launch_counters.py
+++ b/launch/examples/launch_counters.py
@@ -71,7 +71,7 @@ def on_output(event: launch.Event) -> None:
         whoami_cmd = [launch.substitutions.FindExecutable(name='whoami')]
     whoami_action = launch.actions.ExecuteProcess(
         cmd=whoami_cmd,
-        shell=(platform.system() == 'Windows')
+        shell=true
     )
     ld.add_action(whoami_action)
     # Make event handler that uses the output.
```

**Comment by left4taco** [comment]
@wjwwood Now it goes smoothly.
