### ISSUE TITLE
Error passing None target action to OnProcess* event handlers

### ISSUE THREAD

**Issue by jacobperron** [ros2/launch#372]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Binaries or from source
- Version or commit hash:
  - Eloquent or 0822c9711e7d6543a8ba3361e3b5a8db41268c44
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Launch the following launch file with `ros2 launch`:
```python
import launch
import launch_ros

def generate_launch_description():
    talker_node = launch_ros.actions.Node(
        name='talker', package='demo_nodes_cpp', node_executable='talker', output='screen'
    )   
    listener_node = launch_ros.actions.Node(
        name='listener', package='demo_nodes_cpp', node_executable='listener', output='screen'
    )   

    return launch.LaunchDescription([
        # Register an event that starts the listener_node when a process starts
        launch.actions.RegisterEventHandler(
            launch.event_handlers.OnProcessStart(
                target_action=None,
                on_start=listener_node
            )   
        ),  
        # Launch the talker_node
        talker_node
    ])  
```

#### Expected behavior

The talker and listener nodes are started without any errors.

#### Actual behavior

We see the error:

```
AttributeError: 'str' object has no attribute 'perform'
```

Output with --debug option:

<details>
<summary>Debug</summary>
<pre>
[DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[INFO] [launch]: All log files can be found below /home/jacob/.ros/log/2020-01-29-09-44-25-398369-warner-32334
[INFO] [launch]: Default logging verbosity is set to DEBUG
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f913b9fb3c8>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f913b9fb3c8>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7f9131659e48>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f912d5ba128>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f912d5ba128>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7f9131659e48>'
[INFO] [talker-1]: process started with pid [32346]
[DEBUG] [launch.launch_context]: emitting event: 'launch.events.process.ProcessStarted'
[DEBUG] [launch]: processing event: '<launch.events.process.process_started.ProcessStarted object at 0x7f9129441080>'
[DEBUG] [launch]: processing event: '<launch.events.process.process_started.ProcessStarted object at 0x7f9129441080>' ✓ '<launch.event_handlers.on_process_start.OnProcessStart object at 0x7f9129137518>'
[INFO] [listener-2]: process started with pid [32347]
[DEBUG] [launch.launch_context]: emitting event: 'launch.events.process.ProcessStarted'
[DEBUG] [launch]: processing event: '<launch.events.process.process_started.ProcessStarted object at 0x7f9129441780>'
[DEBUG] [launch]: processing event: '<launch.events.process.process_started.ProcessStarted object at 0x7f9129441780>' ✓ '<launch.event_handlers.on_process_start.OnProcessStart object at 0x7f9129137518>'
[DEBUG] [launch]: Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 381, in run_async
    await process_one_event_task
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 291, in _process_one_event
    await self.__process_event(next_event)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 311, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch_ros/actions/node.py", line 370, in execute
    return super().execute(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/execute_process.py", line 715, in execute
    self.__expand_substitutions(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/execute_process.py", line 583, in __expand_substitutions
    else perform_substitutions(context, self.__name)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_context.py", line 184, in perform_substitution
    return substitution.perform(self)
AttributeError: 'str' object has no attribute 'perform'
</pre>
</details>

#### Additional information

We can reproduce the issue if we don't pass a value for `target_action`, which defaults to `None`.

We can also reproduce the same error with `OnProcessExit`, for example:

```python
import launch
import launch_ros

def generate_launch_description():
    talker_node = launch_ros.actions.Node(
        name='talker', package='demo_nodes_cpp', node_executable='talker', output='screen'
    )   
    echo_process = launch.actions.ExecuteProcess(
        name='echo_hello', cmd=['echo', 'hello world!'], output='screen'
    )   

    return launch.LaunchDescription([
        # Register an event that starts the talker_node when a process ends
        launch.actions.RegisterEventHandler(
            launch.event_handlers.OnProcessStart(
                on_start=talker_node
            )
        ),
        # Launch the echo process action
        echo_process
    ])  

```

**Comment by jacobperron** [comment]
Turns out this isn't necessarily a bug, but a pitfall from the design of launch. In my first example, the act of starting the `listener_node` itself is a ProcessStart event, which causes the same instance `listener_node` to be visited again by the launch service. I.e. launch doesn't support visiting the same action more than once.

If we started a copy of the listener node instead, we would end up recursively starting multiple instances of the listener node action, which is not what I was trying to express either. Using the `handle_once` argument will make the launch file do what I want:

```python
import launch
import launch_ros

def generate_launch_description():
    talker_node = launch_ros.actions.Node(
        name='talker', package='demo_nodes_cpp', node_executable='talker', output='screen'
    )   
    listener_node = launch_ros.actions.Node(
        name='listener', package='demo_nodes_cpp', node_executable='listener', output='screen'
    )   

    return launch.LaunchDescription([
        # Register an event that starts the listener_node when a process starts
        launch.actions.RegisterEventHandler(
            launch.event_handlers.OnProcessStart(
                target_action=None,
                on_start=listener_node,
                handle_once=True
            )   
        ),  
        # Launch the talker_node
        talker_node
    ])  
```

To help other users discover that they've fallen into the same pit, I've improved the error message in #375.

**Comment by jacobperron** [comment]
Closing since this isn't a bug and a better guard with error message was introduced in #375 .
