### ISSUE TITLE
[launch_xml] Crash when using set_parameter

### ISSUE THREAD

**Issue by Kettenhoax** [ros2/launch#480]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - foxy latest release
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - not applicable

#### Steps to reproduce issue

If relevant, ros-foxy-launch-xml apt version is 0.10.4-1focal.20201210.045802

Create launch file set_parameter.launch.xml

```xml
<?xml version="1.0"?>
<launch>
    <set_parameter name="use_sim_time" value="true" />
    <node pkg="examples_rclcpp_minimal_publisher" exec="publisher_member_function" output="screen" />
</launch>
```

```bash
ros2 launch set_parameter.launch.xml
```

#### Expected behavior

Launching the xml file should set the `use_sim_time` parameter for the /minimal_publisher node to true.

#### Actual behavior

Launching crashes with this output:

```
[INFO] [launch]: All log files can be found below /root/.ros/log/2021-01-14-09-06-02-650589-L1AAS38-3957
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=InvalidLaunchFileError('xml')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/frontend_launch_file_utilities.py", line 35, in get_launch_description_from_frontend_launch_file
    return parser.parse_description(root_entity)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py", line 97, in parse_description
    actions = [self.parse_action(child) for child in entity.children]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py", line 97, in <listcomp>
    actions = [self.parse_action(child) for child in entity.children]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/parser.py", line 80, in parse_action
    return instantiate_action(entity, self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/frontend/expose.py", line 39, in instantiate_action
    return action_type(**kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/set_parameter.py", line 65, in __init__
    self.__param_dict = normalize_parameter_dict({name: value})
TypeError: unhashable type: 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 273, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 293, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 125, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [xml]: unhashable type: 'list'
```

#### Additional information

Using an equivalent python launch file it works.

```python
# set_parameter.launch.py
from launch import LaunchDescription
from launch_ros.actions import Node, SetParameter


def generate_launch_description():
    return LaunchDescription([
        SetParameter(name='use_sim_time', value=True),
        Node(
            package='examples_rclcpp_minimal_publisher',
            executable='publisher_member_function',
            output='screen',
        ),
    ])
```

```bash
ros2 launch set_parameter.launch.py
ros2 param dump /minimal_publisher
```
outputs
```yaml
minimal_publisher:
  ros__parameters:
    use_sim_time: true
```

**Comment by hidmic** [comment]
Thanks for reporting @Kettenhoax! This is actually an issue in `launch_ros`, and it was resolved in https://github.com/ros2/launch_ros/pull/182 but clearly not backported to Foxy.
