### ISSUE TITLE
Launch files don't shutdown properly with opensplice

### ISSUE THREAD

**Issue by dhood** [ros2/launch#88]
If you run the pub sub example of the new-style launch files with debug hard-coded to True, after a keyboard interrupt you can see all of the shutdown handling (with fastrtps/connext):

```
RMW_IMPLEMENTATION=rmw_fastrtps_cpp python3 src/ros2/launch/launch_ros/examples/pub_sub_launch.py 

...
[INFO] [talker]: Publishing: 'Hello World: 4'
[DEBUG] [launch]: emitting event synchronously: 'launch.events.process.ProcessStdout'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0b1819ef98>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0b1819ef98>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7f0b1b2cf550>'
[INFO] [listener]: I heard: [Hello World: 4]
^C[WARNING] [launch.LaunchService]: user interrupted with ctrl-c (SIGINT)
[INFO] [asyncio]: %r was closed by peer
[INFO] [asyncio]: %r was closed by peer
[DEBUG] [launch]: emitting event: 'launch.events.Shutdown'
[DEBUG] [launch]: emitting event synchronously: 'launch.events.process.ProcessStdout'
[DEBUG] [launch]: emitting event synchronously: 'launch.events.process.ProcessStdout'
[INFO] [asyncio]: %r was closed by peer
[INFO] [asyncio]: %r was closed by peer
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f0b19194f98>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f0b19194f98>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7f0b1819e748>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f0b19194f98>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7f0b1819e0b8>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f0b19194f98>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7f0b1b2cfe10>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f0b19194f98>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7f0b1b2cf390>'
[WARNING] [asyncio]: Executing %s took %.3f seconds
[INFO] [asyncio]: %r exited with return code %r
[INFO] [asyncio]: %r exited with return code %r
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0b14f3f518>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0b14f3f518>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7f0b1b2cf550>'
signal_handler(2)
[INFO] [launch]: process[talker-1]: process has finished cleanly
[DEBUG] [launch]: emitting event: 'launch.events.process.ProcessExited'
[INFO] [launch]: process[listener-2]: process has finished cleanly
[DEBUG] [launch]: emitting event: 'launch.events.process.ProcessExited'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0b14f3f208>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0b14f3f208>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7f0b1b2cf550>'
signal_handler(2)
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_exited.ProcessExited object at 0x7f0b1b2cf5c0>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_exited.ProcessExited object at 0x7f0b1b2cf5c0>' ✓ '<launch.event_handler.EventHandler object at 0x7f0b1b2cf4e0>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_exited.ProcessExited object at 0x7f0b14f3f518>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_exited.ProcessExited object at 0x7f0b14f3f518>' ✓ '<launch.event_handler.EventHandler object at 0x7f0b1b2cf4e0>'
```

But for Opensplice you get a segfault:

```
$ RMW_IMPLEMENTATION=rmw_opensplice_cpp python3 src/ros2/launch/launch_ros/examples/pub_sub_launch.py 
...
[INFO] [talker]: Publishing: 'Hello World: 2'
[DEBUG] [launch]: emitting event synchronously: 'launch.events.process.ProcessStdout'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0975e89e10>'
[DEBUG] [launch.LaunchService]: processing event: '<launch.events.process.process_stdout.ProcessStdout object at 0x7f0975e89e10>' ✓ '<launch.event_handlers.on_process_io.OnProcessIO object at 0x7f0978fac5c0>'
[INFO] [listener]: I heard: [Hello World: 2]
^CSegmentation fault (core dumped)
```

I was not able to produce it with legacy launch but I did notice that it also happens even with only the default ROS launch descriptor included.

**Comment by dhood** [comment]
Update: commenting the launcher's node's [spin_once](https://github.com/ros2/launch/blob/fb896f2bc27fcf11e316c36ca9626b3a6806cd7a/launch_ros/launch_ros/default_launch_description.py#L88) prevents the segfault but the individual nodes still segfault:

```
[INFO] [listener]: I heard: [Hello World: 1]
[INFO] [talker]: Publishing: "Hello World: 2"
[INFO] [listener]: I heard: [Hello World: 2]
^C[WARNING] [launch.LaunchService]: user interrupted with ctrl-c (SIGINT)
[ERROR] [launch]: process[talker-1] process has died [pid 20916, exit code -11, cmd '/home/dhood/ros2_bouncy/install/lib/demo_nodes_py/talker chatter:=my_chatter'].
[ERROR] [launch]: process[listener-2] process has died [pid 20917, exit code -11, cmd '/home/dhood/ros2_bouncy/install/lib/demo_nodes_py/listener chatter:=my_chatter'].
```

**Comment by dhood** [comment]
In the previous comment the launch file was running two python nodes.

If it's running two c++ nodes (with spin_once commented in the launcher still), then they can exit:

```
Starting launch of launch description...

[INFO] [launch]: process[talker-1]: started with pid [21342]
[INFO] [launch]: process[listener-2]: started with pid [21391]
[INFO] [talker]: Publishing: 'Hello World: 1'
[INFO] [listener]: I heard: [Hello World: 1]
^C[WARNING] [launch.LaunchService]: user interrupted with ctrl-c (SIGINT)
[INFO] [talker]: Publishing: 'Hello World: 2'
signal_handler(2)
[INFO] [listener]: I heard: [Hello World: 2]
signal_handler(2)
[INFO] [launch]: process[talker-1]: process has finished cleanly
[INFO] [launch]: process[listener-2]: process has finished cleanly
```

so it seems to be unique to rclpy.

@wjwwood helped me inspect the backtrace and the suspicion is that it's crashing trying to call opensplice's signal handler. Reverting https://github.com/ros2/rclpy/pull/191/files#diff-80dda03110b5be606b823d6b0558b5c2R53 allows the nodes to shutdown, e.g. with launch_ros spinning as usual and launching two python nodes:

```
$ python3 src/ros2/launch/launch_ros/examples/pub_sub_launch.py 
Starting introspection of launch description...

<launch.launch_description.LaunchDescription object at 0x7f9f584751d0>
├── ExecuteProcess(cmd=[Substitution('<launch_ros.substitutions.executable_in_package.ExecutableInPackage object at 0x7f9f5a25d6a0>'), Substitution('<launch.substitutions.local_substitution.LocalSubstitution object at 0x7f9f58480f60>')], cwd=None, env=None, shell=False)
└── ExecuteProcess(cmd=[Substitution('<launch_ros.substitutions.executable_in_package.ExecutableInPackage object at 0x7f9f58475080>'), Substitution('<launch.substitutions.local_substitution.LocalSubstitution object at 0x7f9f58475160>')], cwd=None, env=None, shell=False)

Starting launch of launch description...

[INFO] [launch]: process[talker-1]: started with pid [28887]
[INFO] [launch]: process[listener-2]: started with pid [28888]
[INFO] [talker]: Publishing: "Hello World: 0"
[INFO] [listener]: I heard: [Hello World: 0]
[INFO] [talker]: Publishing: "Hello World: 1"
[INFO] [listener]: I heard: [Hello World: 1]
^CTraceback (most recent call last):
  File "/home/dhood/ros2_bouncy/install/lib/demo_nodes_py/talker", line 11, in <module>
    load_entry_point('demo-nodes-py', 'console_scripts', 'talker')()
  File "/home/dhood/ros2_bouncy/build/demo_nodes_py/demo_nodes_py/topics/talker.py", line 48, in main
    rclpy.spin(node)
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/__init__.py", line 108, in spin
    executor.spin_once()
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/executors.py", line 503, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/executors.py", line 492, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/executors.py", line 415, in _wait_for_ready_callbacks
    raise KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/dhood/ros2_bouncy/install/lib/demo_nodes_py/listener", line 11, in <module>
    load_entry_point('demo-nodes-py', 'console_scripts', 'listener')()
  File "/home/dhood/ros2_bouncy/build/demo_nodes_py/demo_nodes_py/topics/listener.py", line 40, in main
    rclpy.spin(node)
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/__init__.py", line 108, in spin
    executor.spin_once()
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/executors.py", line 503, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/executors.py", line 492, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/home/dhood/ros2_overlay/install_isolated/rclpy/lib/python3.5/site-packages/rclpy/executors.py", line 415, in _wait_for_ready_callbacks
    raise KeyboardInterrupt
KeyboardInterrupt
[ERROR] [launch]: process[listener-2] process has died [pid 28888, exit code 1, cmd '/home/dhood/ros2_bouncy/install/lib/demo_nodes_py/listener chatter:=my_chatter'].
[ERROR] [launch]: process[talker-1] process has died [pid 28887, exit code 1, cmd '/home/dhood/ros2_bouncy/install/lib/demo_nodes_py/talker chatter:=my_chatter'].
sys:1: RuntimeWarning: coroutine 'LaunchContext.emit_event' was never awaited
[ERROR] [asyncio]: Task was destroyed but it is pending!
task: <Task pending coro=<LaunchContext.emit_event() done, defined at src/ros2/launch/launch_ros/examples/../../launch/launch/launch_context.py:172> cb=[_chain_future.<locals>._call_set_state() at /usr/lib/python3.5/asyncio/futures.py:438]>
```

**Comment by dhood** [comment]
Note that on OS X this causes a notification gui popup that python died unexpectedly. It doesn't seem to affect windows.

**Comment by dhood** [comment]
resolved by https://github.com/ros2/rclpy/pull/194
